<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Operations;

use \bolt_dev\bolt\Utils\SpeakeasyMetadata;
class AccountAddPaymentMethodRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public mixed $requestBody;
    
    /**
     * The publicly viewable identifier used to identify a merchant division.
     * 
     * @var string $xPublishableKey
     */
	#[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Publishable-Key')]
    public string $xPublishableKey;
    
	public function __construct()
	{
		$this->requestBody = null;
		$this->xPublishableKey = "";
	}
}
