<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Operations;

use \bolt_dev\bolt\Utils\SpeakeasyMetadata;
class AccountGetSecurity
{
	#[SpeakeasyMetadata('security:option=true')]
    public ?AccountGetSecurityOption1 $option1 = null;
    
	#[SpeakeasyMetadata('security:option=true')]
    public ?AccountGetSecurityOption2 $option2 = null;
    
	public function __construct()
	{
		$this->option1 = null;
		$this->option2 = null;
	}
}
