<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Operations;


class AccountAddressEditResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * The address is invalid and cannot be added
     * 
     * @var mixed $accountAddressEdit400ApplicationJSONOneOf
     */
	
    public mixed $accountAddressEdit400ApplicationJSONOneOf = null;
    
    /**
     * The address was successfully edited
     * 
     * @var ?\bolt_dev\bolt\Models\Shared\AddressListing $addressListing
     */
	
    public ?\bolt_dev\bolt\Models\Shared\AddressListing $addressListing = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->accountAddressEdit400ApplicationJSONOneOf = null;
		$this->addressListing = null;
	}
}
