<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Operations;


class GuestPaymentsInitializeResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Payment token retrieved
     * 
     * @var ?\bolt_dev\bolt\Models\Shared\PaymentMethodInitializeResponse $paymentMethodInitializeResponse
     */
	
    public ?\bolt_dev\bolt\Models\Shared\PaymentMethodInitializeResponse $paymentMethodInitializeResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->paymentMethodInitializeResponse = null;
	}
}
