<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Operations;


class MerchantCallbacksUpdateResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Callbacks URLs were successfully updated
     * 
     * @var ?\bolt_dev\bolt\Models\Shared\CallbackUrls $callbackUrls
     */
	
    public ?\bolt_dev\bolt\Models\Shared\CallbackUrls $callbackUrls = null;
    
    /**
     * The URL is invalid and cannot be set
     * 
     * @var mixed $merchantCallbacksUpdate400ApplicationJSONOneOf
     */
	
    public mixed $merchantCallbacksUpdate400ApplicationJSONOneOf = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->callbackUrls = null;
		$this->merchantCallbacksUpdate400ApplicationJSONOneOf = null;
	}
}
