<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Operations;


class WebhooksGetResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * The specified resource was not found
     * 
     * @var ?\bolt_dev\bolt\Models\Shared\Error $error
     */
	
    public ?\bolt_dev\bolt\Models\Shared\Error $error = null;
    
    /**
     * Webhook information has been retrieved
     * 
     * @var ?\bolt_dev\bolt\Models\Shared\Webhook $webhook
     */
	
    public ?\bolt_dev\bolt\Models\Shared\Webhook $webhook = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->error = null;
		$this->webhook = null;
	}
}
