<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class AccountTestCreationData
{
	#[\JMS\Serializer\Annotation\SerializedName('deactivate_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $deactivateAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('email_state')]
    #[\JMS\Serializer\Annotation\Type('enum<bolt_dev\bolt\Models\Shared\EmailState>')]
    public EmailState $emailState;
    
	#[\JMS\Serializer\Annotation\SerializedName('has_address')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $hasAddress = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('is_migrated')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $isMigrated = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('phone_state')]
    #[\JMS\Serializer\Annotation\Type('enum<bolt_dev\bolt\Models\Shared\PhoneState>')]
    public PhoneState $phoneState;
    
	public function __construct()
	{
		$this->deactivateAt = new \DateTime();
		$this->emailState = \bolt_dev\bolt\Models\Shared\EmailState::Missing;
		$this->hasAddress = null;
		$this->isMigrated = null;
		$this->phoneState = \bolt_dev\bolt\Models\Shared\PhoneState::Missing;
	}
}
