<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class AccountTestCreationDataOutput
{
	#[\JMS\Serializer\Annotation\SerializedName('deactivate_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $deactivateAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $email;
    
	#[\JMS\Serializer\Annotation\SerializedName('email_state')]
    #[\JMS\Serializer\Annotation\Type('enum<bolt_dev\bolt\Models\Shared\EmailState>')]
    public EmailState $emailState;
    
	#[\JMS\Serializer\Annotation\SerializedName('oauth_code')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $oauthCode;
    
	#[\JMS\Serializer\Annotation\SerializedName('otp_code')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $otpCode;
    
	#[\JMS\Serializer\Annotation\SerializedName('phone')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $phone;
    
	#[\JMS\Serializer\Annotation\SerializedName('phone_state')]
    #[\JMS\Serializer\Annotation\Type('enum<bolt_dev\bolt\Models\Shared\PhoneState>')]
    public PhoneState $phoneState;
    
	public function __construct()
	{
		$this->deactivateAt = new \DateTime();
		$this->email = "";
		$this->emailState = \bolt_dev\bolt\Models\Shared\EmailState::Missing;
		$this->oauthCode = "";
		$this->otpCode = "";
		$this->phone = "";
		$this->phoneState = \bolt_dev\bolt\Models\Shared\PhoneState::Missing;
	}
}
