<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class AddressErrorInvalidRegion
{
    /**
     * The type of error returned
     * 
     * @var \bolt_dev\bolt\Models\Shared\AddressErrorInvalidRegionTag $dotTag
     */
	#[\JMS\Serializer\Annotation\SerializedName('.tag')]
    #[\JMS\Serializer\Annotation\Type('enum<bolt_dev\bolt\Models\Shared\AddressErrorInvalidRegionTag>')]
    public AddressErrorInvalidRegionTag $dotTag;
    
    /**
     * A human-readable error message, which might include information specific to
     * 
     * the request that was made.
     * 
     * 
     * @var string $message
     */
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $message;
    
	public function __construct()
	{
		$this->dotTag = \bolt_dev\bolt\Models\Shared\AddressErrorInvalidRegionTag::InvalidRegion;
		$this->message = "";
	}
}
