<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class AddressReferenceId
{
    /**
     * The type of address reference
     * 
     * @var \bolt_dev\bolt\Models\Shared\AddressReferenceIdTag $dotTag
     */
	#[\JMS\Serializer\Annotation\SerializedName('.tag')]
    #[\JMS\Serializer\Annotation\Type('enum<bolt_dev\bolt\Models\Shared\AddressReferenceIdTag>')]
    public AddressReferenceIdTag $dotTag;
    
    /**
     * The address's ID
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
	public function __construct()
	{
		$this->dotTag = \bolt_dev\bolt\Models\Shared\AddressReferenceIdTag::Id;
		$this->id = "";
	}
}
