<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class Amounts
{
	#[\JMS\Serializer\Annotation\SerializedName('currency')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $currency;
    
    /**
     * The total tax amount, in cents for all of the items associated with the cart.
     * 
     * @var ?int $tax
     */
	#[\JMS\Serializer\Annotation\SerializedName('tax')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $tax = null;
    
    /**
     * The total amount, in cents, including its items and taxes (if applicable).
     * 
     * @var int $total
     */
	#[\JMS\Serializer\Annotation\SerializedName('total')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $total;
    
	public function __construct()
	{
		$this->currency = "";
		$this->tax = null;
		$this->total = 0;
	}
}
