<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


/** The type of error returned */
enum CallbackUrlErrorInvalidUrlTag: string
{
    case InvalidUrl = 'invalid_url';
}
