<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


/**
 * CallbackUrls - Callbacks URLs were successfully retrieved
 * 
 * @package bolt_dev\bolt\Models\Shared
 * @access public
 */
class CallbackUrls
{
	#[\JMS\Serializer\Annotation\SerializedName('account_page')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $accountPage = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('base_domain')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $baseDomain = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('confirmation_redirect')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $confirmationRedirect = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('create_order')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $createOrder = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('debug')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $debug = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('get_account')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $getAccount = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('mobile_app_domain')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mobileAppDomain = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('oauth_logout')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $oauthLogout = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('oauth_redirect')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $oauthRedirect = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('privacy_policy')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $privacyPolicy = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('product_info')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $productInfo = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('remote_api')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $remoteApi = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('shipping')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $shipping = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('support_page')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $supportPage = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('tax')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tax = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('terms_of_service')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $termsOfService = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('universal_merchant_api')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $universalMerchantApi = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('update_cart')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $updateCart = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('validate_additional_account_data')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $validateAdditionalAccountData = null;
    
	public function __construct()
	{
		$this->accountPage = null;
		$this->baseDomain = null;
		$this->confirmationRedirect = null;
		$this->createOrder = null;
		$this->debug = null;
		$this->getAccount = null;
		$this->mobileAppDomain = null;
		$this->oauthLogout = null;
		$this->oauthRedirect = null;
		$this->privacyPolicy = null;
		$this->productInfo = null;
		$this->remoteApi = null;
		$this->shipping = null;
		$this->supportPage = null;
		$this->tax = null;
		$this->termsOfService = null;
		$this->universalMerchantApi = null;
		$this->updateCart = null;
		$this->validateAdditionalAccountData = null;
	}
}
