<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class CartShipment
{
	#[\JMS\Serializer\Annotation\SerializedName('address')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public mixed $address = null;
    
    /**
     * The name of the carrier selected.
     * 
     * @var ?string $carrier
     */
	#[\JMS\Serializer\Annotation\SerializedName('carrier')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $carrier = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('cost')]
    #[\JMS\Serializer\Annotation\Type('bolt_dev\bolt\Models\Shared\Amounts')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Amounts $cost = null;
    
	public function __construct()
	{
		$this->address = null;
		$this->carrier = null;
		$this->cost = null;
	}
}
