<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class Cart
{
	#[\JMS\Serializer\Annotation\SerializedName('amounts')]
    #[\JMS\Serializer\Annotation\Type('bolt_dev\bolt\Models\Shared\Amounts')]
    public Amounts $amounts;
    
    /**
     * $discounts
     * 
     * @var ?array<\bolt_dev\bolt\Models\Shared\CartDiscount> $discounts
     */
	#[\JMS\Serializer\Annotation\SerializedName('discounts')]
    #[\JMS\Serializer\Annotation\Type('array<bolt_dev\bolt\Models\Shared\CartDiscount>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $discounts = null;
    
    /**
     * This field corresponds to the merchant's order reference associated with this Bolt transaction.
     * 
     * @var ?string $displayId
     */
	#[\JMS\Serializer\Annotation\SerializedName('display_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $displayId = null;
    
    /**
     * $items
     * 
     * @var ?array<\bolt_dev\bolt\Models\Shared\CartItem> $items
     */
	#[\JMS\Serializer\Annotation\SerializedName('items')]
    #[\JMS\Serializer\Annotation\Type('array<bolt_dev\bolt\Models\Shared\CartItem>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $items = null;
    
    /**
     * Used optionally to pass additional information like order numbers or other IDs as needed.
     * 
     * @var ?string $orderDescription
     */
	#[\JMS\Serializer\Annotation\SerializedName('order_description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $orderDescription = null;
    
    /**
     * This value is used by Bolt as an external reference to a given order. This reference must be unique per successful transaction.
     * 
     * @var string $orderReference
     */
	#[\JMS\Serializer\Annotation\SerializedName('order_reference')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $orderReference;
    
    /**
     * $shipments
     * 
     * @var ?array<\bolt_dev\bolt\Models\Shared\CartShipment> $shipments
     */
	#[\JMS\Serializer\Annotation\SerializedName('shipments')]
    #[\JMS\Serializer\Annotation\Type('array<bolt_dev\bolt\Models\Shared\CartShipment>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $shipments = null;
    
	public function __construct()
	{
		$this->amounts = new \bolt_dev\bolt\Models\Shared\Amounts();
		$this->discounts = null;
		$this->displayId = null;
		$this->items = null;
		$this->orderDescription = null;
		$this->orderReference = "";
		$this->shipments = null;
	}
}
