<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


/**
 * Error - The specified resource was not found
 * 
 * @package bolt_dev\bolt\Models\Shared
 * @access public
 */
class Error
{
    /**
     * The type of error returned
     * 
     * @var string $dotTag
     */
	#[\JMS\Serializer\Annotation\SerializedName('.tag')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $dotTag;
    
    /**
     * A human-readable error message, which might include information specific to
     * 
     * the request that was made.
     * 
     * 
     * @var string $message
     */
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $message;
    
	public function __construct()
	{
		$this->dotTag = "";
		$this->message = "";
	}
}
