<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class EventList
{
	#[\JMS\Serializer\Annotation\SerializedName('.tag')]
    #[\JMS\Serializer\Annotation\Type('enum<bolt_dev\bolt\Models\Shared\EventListTag>')]
    public EventListTag $dotTag;
    
    /**
     * $eventList
     * 
     * @var array<\bolt_dev\bolt\Models\Shared\EventListEventList> $eventList
     */
	#[\JMS\Serializer\Annotation\SerializedName('event_list')]
    #[\JMS\Serializer\Annotation\Type('array<enum<bolt_dev\bolt\Models\Shared\EventListEventList>>')]
    public array $eventList;
    
	public function __construct()
	{
		$this->dotTag = \bolt_dev\bolt\Models\Shared\EventListTag::List;
		$this->eventList = [];
	}
}
