<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


enum EventListEventList: string
{
    case Payment = 'payment';
    case Credit = 'credit';
    case Capture = 'capture';
    case Void = 'void';
    case Auth = 'auth';
    case Pending = 'pending';
    case RejectedIrreversible = 'rejected_irreversible';
    case RejectedReversible = 'rejected_reversible';
    case FailedPayment = 'failed_payment';
    case NewsletterSubscription = 'newsletter_subscription';
    case RiskInsights = 'risk_insights';
    case CreditCardDeleted = 'credit_card_deleted';
}
