<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;

use \bolt_dev\bolt\Utils\SpeakeasyMetadata;
/**
 * Identifier - A type and value combination that defines the identifier used to detect
 * 
 * the existence of an account.
 * 
 * 
 * @package bolt_dev\bolt\Models\Shared
 * @access public
 */
class Identifier
{
    /**
     * The type of identifier
     * 
     * @var \bolt_dev\bolt\Models\Shared\IdentifierIdentifierType $identifierType
     */
	#[SpeakeasyMetadata('queryParam:name=identifier_type')]
    public IdentifierIdentifierType $identifierType;
    
    /**
     * The value of the identifier. The value must be valid for the specified `identifier_type`
     * 
     * @var string $identifierValue
     */
	#[SpeakeasyMetadata('queryParam:name=identifier_value')]
    public string $identifierValue;
    
	public function __construct()
	{
		$this->identifierType = \bolt_dev\bolt\Models\Shared\IdentifierIdentifierType::Email;
		$this->identifierValue = "";
	}
}
