<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class Identifiers
{
    /**
     * $merchantDivisions
     * 
     * @var array<\bolt_dev\bolt\Models\Shared\IdentifiersMerchantDivisions> $merchantDivisions
     */
	#[\JMS\Serializer\Annotation\SerializedName('merchant_divisions')]
    #[\JMS\Serializer\Annotation\Type('array<bolt_dev\bolt\Models\Shared\IdentifiersMerchantDivisions>')]
    public array $merchantDivisions;
    
	#[\JMS\Serializer\Annotation\SerializedName('merchant_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $merchantId;
    
	#[\JMS\Serializer\Annotation\SerializedName('signing_secret')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $signingSecret;
    
	public function __construct()
	{
		$this->merchantDivisions = [];
		$this->merchantId = "";
		$this->signingSecret = "";
	}
}
