<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class MerchantDivisions
{
	#[\JMS\Serializer\Annotation\SerializedName('publishable_key')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $publishableKey;
    
	public function __construct()
	{
		$this->publishableKey = "";
	}
}
