<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


/** The credit card network. */
enum Network: string
{
    case Visa = 'visa';
    case Mastercard = 'mastercard';
    case Amex = 'amex';
    case Discover = 'discover';
    case Jcb = 'jcb';
    case Unionpay = 'unionpay';
    case Alliancedata = 'alliancedata';
    case Citiplcc = 'citiplcc';
}
