<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class PaymentMethodInitializeRequest
{
	#[\JMS\Serializer\Annotation\SerializedName('cart')]
    #[\JMS\Serializer\Annotation\Type('bolt_dev\bolt\Models\Shared\Cart')]
    public Cart $cart;
    
	#[\JMS\Serializer\Annotation\SerializedName('payment_method')]
    #[\JMS\Serializer\Annotation\Type('bolt_dev\bolt\Models\Shared\PaymentMethodSavedPaymentMethod')]
    public PaymentMethodSavedPaymentMethod $paymentMethod;
    
	public function __construct()
	{
		$this->cart = new \bolt_dev\bolt\Models\Shared\Cart();
		$this->paymentMethod = new \bolt_dev\bolt\Models\Shared\PaymentMethodSavedPaymentMethod();
	}
}
