<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class PaymentMethodPaypal
{
	#[\JMS\Serializer\Annotation\SerializedName('.tag')]
    #[\JMS\Serializer\Annotation\Type('enum<bolt_dev\bolt\Models\Shared\PaymentMethodPaypalTag>')]
    public PaymentMethodPaypalTag $dotTag;
    
    /**
     * Redirect URL for canceled PayPal transaction.
     * 
     * @var string $cancel
     */
	#[\JMS\Serializer\Annotation\SerializedName('cancel')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $cancel;
    
    /**
     * Redirect URL for successful PayPal transaction.
     * 
     * @var string $success
     */
	#[\JMS\Serializer\Annotation\SerializedName('success')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $success;
    
	public function __construct()
	{
		$this->dotTag = \bolt_dev\bolt\Models\Shared\PaymentMethodPaypalTag::Paypal;
		$this->cancel = "";
		$this->success = "";
	}
}
