<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class PaymentMethodInitializeResponseAction
{
	#[\JMS\Serializer\Annotation\SerializedName('method')]
    #[\JMS\Serializer\Annotation\Type('enum<bolt_dev\bolt\Models\Shared\PaymentMethodInitializeResponseActionMethod>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?PaymentMethodInitializeResponseActionMethod $method = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<bolt_dev\bolt\Models\Shared\PaymentMethodInitializeResponseActionType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?PaymentMethodInitializeResponseActionType $type = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $url = null;
    
	public function __construct()
	{
		$this->method = null;
		$this->type = null;
		$this->url = null;
	}
}
