<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


/** Credit card type */
enum PaymentMethodCreditCardType: string
{
    case Credit = 'credit';
    case Plcc = 'plcc';
}
