<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class PaymentMethodInitializeResponse
{
	#[\JMS\Serializer\Annotation\SerializedName('action')]
    #[\JMS\Serializer\Annotation\Type('bolt_dev\bolt\Models\Shared\PaymentMethodInitializeResponseAction')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?PaymentMethodInitializeResponseAction $action = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<bolt_dev\bolt\Models\Shared\PaymentMethodInitializeResponseStatus>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?PaymentMethodInitializeResponseStatus $status = null;
    
	public function __construct()
	{
		$this->action = null;
		$this->id = null;
		$this->status = null;
	}
}
