<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class PaymentMethodSavedPaymentMethod
{
	#[\JMS\Serializer\Annotation\SerializedName('.tag')]
    #[\JMS\Serializer\Annotation\Type('enum<bolt_dev\bolt\Models\Shared\PaymentMethodSavedPaymentMethodTag>')]
    public PaymentMethodSavedPaymentMethodTag $dotTag;
    
    /**
     * Payment ID of the saved Bolt Payment method.
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
	public function __construct()
	{
		$this->dotTag = \bolt_dev\bolt\Models\Shared\PaymentMethodSavedPaymentMethodTag::SavedPaymentMethod;
		$this->id = "";
	}
}
