<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class ShipmentTrackingUpdate
{
    /**
     * The shipment's actual or estimated delivery date.
     * 
     * @var ?\DateTime $deliveryDate
     */
	#[\JMS\Serializer\Annotation\SerializedName('delivery_date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $deliveryDate = null;
    
    /**
     * The shipment's status.
     * 
     * @var \bolt_dev\bolt\Models\Shared\ShipmentTrackingUpdateStatus $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<bolt_dev\bolt\Models\Shared\ShipmentTrackingUpdateStatus>')]
    public ShipmentTrackingUpdateStatus $status;
    
    /**
     * A list of tracking updates that contain the shipment's status, location, and any unique messages.
     * 
     * @var array<\bolt_dev\bolt\Models\Shared\ShipmentTrackingUpdateTrackingDetails> $trackingDetails
     */
	#[\JMS\Serializer\Annotation\SerializedName('tracking_details')]
    #[\JMS\Serializer\Annotation\Type('array<bolt_dev\bolt\Models\Shared\ShipmentTrackingUpdateTrackingDetails>')]
    public array $trackingDetails;
    
    /**
     * The carrier's tracking number for the shipment. Must be prefixed with `MockBolt`.
     * 
     * @var string $trackingNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('tracking_number')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $trackingNumber;
    
	public function __construct()
	{
		$this->deliveryDate = null;
		$this->status = \bolt_dev\bolt\Models\Shared\ShipmentTrackingUpdateStatus::InTransit;
		$this->trackingDetails = [];
		$this->trackingNumber = "";
	}
}
