<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


enum ShipmentTrackingUpdateTrackingDetailsStatus: string
{
    case Unknown = 'unknown';
    case PreTransit = 'pre_transit';
    case InTransit = 'in_transit';
    case OutForDelivery = 'out_for_delivery';
    case Delivered = 'delivered';
    case AvailableForPickup = 'available_for_pickup';
    case ReturnToSender = 'return_to_sender';
    case Failure = 'failure';
    case Cancelled = 'cancelled';
    case Error = 'error';
}
