<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


class ShipmentTrackingUpdateTrackingDetails
{
    /**
     * The country associated this this set of tracking details, if any.
     * 
     * @var ?string $countryCode
     */
	#[\JMS\Serializer\Annotation\SerializedName('country_code')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $countryCode = null;
    
    /**
     * The tracking detail's timestamp.
     * 
     * @var ?string $eventDate
     */
	#[\JMS\Serializer\Annotation\SerializedName('event_date')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $eventDate = null;
    
    /**
     * The locality associated this this set of tracking details, if any.
     * 
     * @var ?string $locality
     */
	#[\JMS\Serializer\Annotation\SerializedName('locality')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $locality = null;
    
    /**
     * An arbitrary, human-readable message associated with this set of tracking details.
     * 
     * @var ?string $message
     */
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $message = null;
    
    /**
     * The postal associated this this set of tracking details, if any.
     * 
     * @var ?string $postalCode
     */
	#[\JMS\Serializer\Annotation\SerializedName('postal_code')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $postalCode = null;
    
    /**
     * The region associated this this set of tracking details, if any.
     * 
     * @var ?string $region
     */
	#[\JMS\Serializer\Annotation\SerializedName('region')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $region = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<bolt_dev\bolt\Models\Shared\ShipmentTrackingUpdateTrackingDetailsStatus>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ShipmentTrackingUpdateTrackingDetailsStatus $status = null;
    
	public function __construct()
	{
		$this->countryCode = null;
		$this->eventDate = null;
		$this->locality = null;
		$this->message = null;
		$this->postalCode = null;
		$this->region = null;
		$this->status = null;
	}
}
