<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt\Models\Shared;


/** The shipment's status. */
enum ShipmentTrackingUpdateStatus: string
{
    case InTransit = 'in_transit';
    case Cancelled = 'cancelled';
    case Failure = 'failure';
    case Delivered = 'delivered';
}
