<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt;

/**
 * BoltEmbed - Bolt API Reference: A comprehensive Bolt API reference for interacting with Transactions, Orders, Product Catalog, Configuration, Testing, and much more.
 * 
 * @package bolt_dev\bolt
 * @access public
 */
class BoltEmbed
{
	public const SERVERS = [
		'https://api.{username}.dev.bolt.me/v3',
		'https://{environment}.bolt.com/v3',
	];
  	
    /**
     * Account endpoints allow you to view and manage shoppers' accounts. For example,
     * 
     * you can add or remove addresses and payment information.
     * 
     * 
     * @var Account $$account
     */
	public Account $account;
	
    /**
     * Merchant configuration endpoints allow you to retrieve and configure merchant-level
     * 
     * configuration, such as callback URLs, identifiers, secrets, etc...
     * 
     * 
     * @var Configuration $$configuration
     */
	public Configuration $configuration;
	
    /**
     * Use the Payments API to tokenize and process alternative payment methods including Paypal with Bolt. This API is for the Bolt
     * 
     * Accounts package.
     * 
     * 
     * @var Payments $$payments
     */
	public Payments $payments;
	
    /**
     * Endpoints that allow you to generate and retrieve test data to verify certain
     * 
     * flows in non-production environments.
     * 
     * 
     * @var Testing $$testing
     */
	public Testing $testing;
	
    /**
     * Set up webhooks to notify your backend of events within Bolt. These webhooks
     * 
     * can communicate with your OMS or other systems to keep them up to date with Bolt.
     * 
     * 
     * @var Webhooks $$webhooks
     */
	public Webhooks $webhooks;
		
	private SDKConfiguration $sdkConfiguration;

	/**
	 * Returns a new instance of the SDK builder used to configure and create the SDK instance.
	 * 
	 * @return BoltEmbedBuilder
	 */
	public static function builder(): BoltEmbedBuilder
	{
		return new BoltEmbedBuilder();
	}

	/**
	 * @param SDKConfiguration $sdkConfiguration
	 */
	public function __construct(SDKConfiguration $sdkConfiguration)
	{
		$this->sdkConfiguration = $sdkConfiguration;
		
		$this->account = new Account($this->sdkConfiguration);
		
		$this->configuration = new Configuration($this->sdkConfiguration);
		
		$this->payments = new Payments($this->sdkConfiguration);
		
		$this->testing = new Testing($this->sdkConfiguration);
		
		$this->webhooks = new Webhooks($this->sdkConfiguration);
	}
}