<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace bolt_dev\bolt;

class Payments 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * Initialize a Bolt payment for guest shoppers
     * 
     * Initialize a Bolt payment token that will be used to reference this payment to
     * Bolt when it is updated or finalized for guest shoppers.
     * 
     * 
     * @param \bolt_dev\bolt\Models\Operations\GuestPaymentsInitializeRequest $request
     * @return \bolt_dev\bolt\Models\Operations\GuestPaymentsInitializeResponse
     */
	public function initializeGuestPayment(
        \bolt_dev\bolt\Models\Operations\GuestPaymentsInitializeRequest $request,
    ): \bolt_dev\bolt\Models\Operations\GuestPaymentsInitializeResponse
    {
        $baseUrl = Utils\Utils::templateUrl($this->sdkConfiguration->getServerUrl(), $this->sdkConfiguration->getServerDefaults());
        $url = Utils\Utils::generateUrl($baseUrl, '/guest/payments');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "guestPaymentMethodInitializeRequest", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \bolt_dev\bolt\Models\Operations\GuestPaymentsInitializeResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->paymentMethodInitializeResponse = $serializer->deserialize((string)$httpResponse->getBody(), 'bolt_dev\bolt\Models\Shared\PaymentMethodInitializeResponse', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Initialize a Bolt payment for logged in shoppers
     * 
     * Initialize a Bolt payment token that will be used to reference this payment to
     * Bolt when it is updated or finalized for logged in shoppers.
     * 
     * 
     * @param \bolt_dev\bolt\Models\Operations\PaymentsInitializeRequest $request
     * @param \bolt_dev\bolt\Models\Operations\PaymentsInitializeSecurity $security
     * @return \bolt_dev\bolt\Models\Operations\PaymentsInitializeResponse
     */
	public function initializeLoggedInPayment(
        \bolt_dev\bolt\Models\Operations\PaymentsInitializeRequest $request,
        \bolt_dev\bolt\Models\Operations\PaymentsInitializeSecurity $security,
    ): \bolt_dev\bolt\Models\Operations\PaymentsInitializeResponse
    {
        $baseUrl = Utils\Utils::templateUrl($this->sdkConfiguration->getServerUrl(), $this->sdkConfiguration->getServerDefaults());
        $url = Utils\Utils::generateUrl($baseUrl, '/payments');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "paymentMethodInitializeRequest", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $client = Utils\Utils::configureSecurityClient($this->sdkConfiguration->defaultClient, $security);
        $httpResponse = $client->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \bolt_dev\bolt\Models\Operations\PaymentsInitializeResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->paymentMethodInitializeResponse = $serializer->deserialize((string)$httpResponse->getBody(), 'bolt_dev\bolt\Models\Shared\PaymentMethodInitializeResponse', 'json');
            }
        }

        return $response;
    }
}